# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pyasuko <pyasuko@student.21-school.ru>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/29 13:27:16 by pyasuko           #+#    #+#              #
#    Updated: 2021/03/15 20:36:22 by pyasuko          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM debian:buster
RUN apt update && apt install -y	vim \
									nginx \
									mariadb-server \
									curl \
									php-mysql \
									php-fpm \
									php \
									wget
